const number1 = 5;
const number2 = 11;
const product = number1 * number2;
console.log(product);
console.log(typeof product);
const charge = 14;
const payment = 2;
const amountRemaining = charge - payment;
console.log(amountRemaining);
console.log(typeof amountRemaining);
const tests = 7;
const assignments = 18;
const final = 11;
const grade = tests + assignments + final / 3;
console.log(grade);
console.log(typeof grade);
const firstName = 'Israel';
const lastName = ' Aguilar';
const fullName = firstName + lastName;
console.log(fullName);
console.log(typeof fullName);
const pH = 25;
const isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
const numberOfSoldiers = 9000;
const isSparta = 300 === numberOfSoldiers;
console.log(isSparta);
console.log(typeof isSparta);
let nickname = fullName;
nickname += ' is the GOAT';
console.log(nickname);
console.log(typeof nickname);
